
version: '3.8'

services:
  app:
    image: myapp_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager_app
    ports:
      - "5000:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - taskmanager_network

  db:
    image: mysql:8
    container_name: taskmanager_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
    ports:
      - "3306:3306"
    networks:
      - taskmanager_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  taskmanager_network:
    driver: bridge

volumes:
  db_data:
